### ISSUE TITLE
<link> tag followed by <script> tag renders self closing <script> tag.

### ISSUE THREAD

**Issue by tboloo** [figdice/figdice#6] opened 2016-01-01 21:26 UTC
I found the peculiar behaviour when rendering the `<script>` tag with figdice 2.3
```xml
$template = <<<TEMPLATE
<fig:template xmlns:fig="http://www.figdice.org/">
        <link href="/assets/style.css" rel="stylesheet" />
        <script src="/assets/require.js"></script>
</fig:template>
TEMPLATE;
```
renders incorrectly `<script>` tag as 
```html
<link href="/assets/style.css" rel="stylesheet" />
        <script src="/assets/require.js" />
```
whereas reversed order, that is 
```xml
$template = <<<TEMPLATE
<fig:template xmlns:fig="http://www.figdice.org/">
        <script src="/assets/require.js"></script>
        <link href="/assets/style.css" rel="stylesheet" />
</fig:template>
TEMPLATE;
```
renders expected (and correct) result
```html
<script src="/assets/require.js"></script>
        <link href="/assets/style.css" rel="stylesheet" />
```
Behaviour is only present when the namespace is defined, code without the namespace renders correctly regardles of the order.

**Comment by gabrielzerbib** [comment] 2016-01-02 19:15
Hi Bolek,
You are right. I did encounter sometimes this auto-closing issue about `script` tags (and other tags with no contents, but whose closing tag is explicit in the template). Yet it never occurred to me that it was somehow related to the declaration of the `xmlns` namespace.
I think that the problem is to be found in this part:
https://github.com/gabrielzerbib/figdice/blob/master/src/figdice/View.php#L607-L620

I will see what I can do -- and any ideas/patches are welcome!
Thanks

**Comment by gabrielzerbib** [comment] 2016-01-02 20:15
As stated in this PHP user comment: http://php.net/manual/en/function.xml-get-current-byte-index.php#56953
the behaviour of xml_get_current_byte_index is dependent on the implementation of the XML parser, and I don't know what progress was made in this field over all these years.
I am trying to simplify the parsing in this new branch https://github.com/gabrielzerbib/figdice/tree/script-autoclose-bug
Please and let me know if it's better on your platform: we need to check further on Windows, and in in included sub-templates.
Thanks.

**Comment by gabrielzerbib** [comment] 2016-01-03 10:07
Tested this morning on Windows Seven with PHP 5.4 & libxml 2.7.8, and with PHP 5.5 & libxml 2.9.0.
I think the problem is solved. Please let me know if you found otherwise. Thanks.

**Comment by tboloo** [comment] 2016-01-04 22:09
Hi Gabriel,
I have tested the `script-autoclose-bug` branch on my developer machine _(Mac OS X, PHP 5.6.14)_ as well as on production one _(Debian 7 Wheezy, PHP 5.6.8-1~dotdeb+wheezy.1)_, and it works fine - all the tests pass, and the problematic code from the issue renders correctly.
When do you intend to push it into the release?

**Comment by figdice** [comment] 2016-01-05 08:27
Merged in master. Thanks for the tests!

**Closed** 2016-01-05 08:28 UTC
Labels: bug
